controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

cartesAll:
    # id est dynamique ici
    path: /cartesAll/
    controller: App\Controller\CartesAllController::index

cartesPerso:
    # id est dynamique ici
    path: /cartesPerso/
    controller: App\Controller\CartesPersoController::index

creationCarte:
    # id est dynamique ici
    path: /creation/
    controller: App\Controller\CreationCarteController::index

modifCarte:
    # id est dynamique ici
    path: /modif/
    controller: App\Controller\ModifCarteController::index