controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

contact:
    path: /contact
    controller: App\Controller\ContactController::index

accueil:
    path: /
    controller: App\Controller\HomeController::index

contactModify:
    path: /contact/modify{id}
    controller: App\Controller\ContactController::modify
    requirements:
        id: '\d'

contactDelete:
    path: /contact/delete{id}
    controller: App\Controller\ContactController::delete
    requirements:
        id: '\d'

yugioh:
    path: '/yugioh/cardinfo'
    controller: 'App\Controller\HomeController::getCardInfo'
    methods: ['GET']
