controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

contact:
    path: /contact
    controller: App\Controller\ContactController::index

accueil:
    path: /
    controller: App\Controller\HomeController::index

contactModify:
    # id est dynamique ici
    path: /contact/modify{id}
    # après les "::", c'est la méthode appellée
    controller: App\Controller\ContactController::modify
    # force l'utilisation d'un caracctère, ici un nombre
    requirements:
        id: '\d'

creationCard:
    # id est dynamique ici
    path: /creation/
    controller: App\Controller\CreationController::index

modificationCard:
    # id est dynamique ici
    path: /modification/
    controller: App\Controller\ModificationController::index

persoCard:
    # id est dynamique ici
    path: /perso/
    controller: App\Controller\PersoController::index
    
   
  

contactDelete:
    # id est dynamique ici
    path: /contact/delete{id}
    # après les "::", c'est la méthode appellée
    controller: App\Controller\ContactController::delete
    # force l'utilisation d'un caracctère, ici un nombre
    requirements:
        id: '\d'